# This file was generated by GoReleaser. DO NOT EDIT.
cask "gdeck" do
  version "0.1.3-rc.2"

  on_macos do
    on_intel do
      sha256 "c214e50fd8195dd598d0d9b926acd362ffb12786ab561ca486f7b3a1e95682ac"
      url "https://github.com/Nunokawa-Lab/gdeck/releases/download/v#{version}/gdeck-darwin-amd64",
        verified: "github.com/Nunokawa-Lab/gdeck/"
      binary "gdeck-darwin-amd64", target: "gdeck"
    end
    on_arm do
      sha256 "a19c100f1bf8744ea6fcc2eae1b0451818e72389f0d50a9c9d3a51350f1eaa6e"
      url "https://github.com/Nunokawa-Lab/gdeck/releases/download/v#{version}/gdeck-darwin-arm64",
        verified: "github.com/Nunokawa-Lab/gdeck/"
      binary "gdeck-darwin-arm64", target: "gdeck"
    end
  end

  on_linux do
    on_intel do
      sha256 "9fb9d41228d1d9b8ed1c341e0748dd5083c551df939e9b70ad00d0445d3d9b0d"
      url "https://github.com/Nunokawa-Lab/gdeck/releases/download/v#{version}/gdeck-linux-amd64",
        verified: "github.com/Nunokawa-Lab/gdeck/"
      binary "gdeck-linux-amd64", target: "gdeck"
    end
    on_arm do
      sha256 "329c89363f9248b0a65101017c5b07f653ef161a2100d3f43edb8c96da713350"
      url "https://github.com/Nunokawa-Lab/gdeck/releases/download/v#{version}/gdeck-linux-arm64",
        verified: "github.com/Nunokawa-Lab/gdeck/"
      binary "gdeck-linux-arm64", target: "gdeck"
    end
  end

  name "gdeck"
  desc "Lightweight API testing tool (CLI + TUI)"
  homepage "https://github.com/Nunokawa-Lab/gdeck"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      Dir.glob("#{staged_path}/*", File::FNM_DOTMATCH).each do |path|
        next unless File.file?(path)
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", path]
      end
    end
  end

  # No zap stanza required

  caveats <<~EOS
    ____ ____  _____ ____ _  __
    / ___|  _ \\| ____/ ___| |/ /
    | |  _| | | |  _|| |   | ' /
    | |_| | |_| | |__| |___| .
    \\____|____/|_____\\____|_|\\_

    Run `gdeck --help` to get started, or `gdeck tui` for the interactive UI.
  EOS
end
