# This file was generated by GoReleaser. DO NOT EDIT.
cask "gdeck" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "a6719eed9614dd50140f1c92c9645c739d1130d503e026f942beac01b45b00de"
      url "https://github.com/Nunokawa-Lab/gdeck/releases/download/v#{version}/gdeck-darwin-amd64",
        verified: "github.com/Nunokawa-Lab/gdeck/"
      binary "gdeck-darwin-amd64", target: "gdeck"
    end
    on_arm do
      sha256 "4729d5424faddfbf515cfd2c4a4f4a7f1a7e93b473734c0202bdf6f21263260d"
      url "https://github.com/Nunokawa-Lab/gdeck/releases/download/v#{version}/gdeck-darwin-arm64",
        verified: "github.com/Nunokawa-Lab/gdeck/"
      binary "gdeck-darwin-arm64", target: "gdeck"
    end
  end

  on_linux do
    on_intel do
      sha256 "5e1cfa4dffe1c7b215f0045ef00b2373e00acc520dc6bc48f14c5631842d6820"
      url "https://github.com/Nunokawa-Lab/gdeck/releases/download/v#{version}/gdeck-linux-amd64",
        verified: "github.com/Nunokawa-Lab/gdeck/"
      binary "gdeck-linux-amd64", target: "gdeck"
    end
    on_arm do
      sha256 "a927d5d79ecbf460c56bbcd59316ee990833d55cfbdbf2b554ff4f2c5adb3079"
      url "https://github.com/Nunokawa-Lab/gdeck/releases/download/v#{version}/gdeck-linux-arm64",
        verified: "github.com/Nunokawa-Lab/gdeck/"
      binary "gdeck-linux-arm64", target: "gdeck"
    end
  end

  name "gdeck"
  desc "Lightweight API testing tool (CLI + TUI)"
  homepage "https://github.com/Nunokawa-Lab/gdeck"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      Dir.glob("#{staged_path}/*", File::FNM_DOTMATCH).each do |path|
        next unless File.file?(path)
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", path]
      end
    end
  end

  # No zap stanza required

  caveats <<~EOS
    ​        ____ ____  _____ ____ _  __
           / ___|  _ \\| ____/ ___| |/ /
          | |  _| | | |  _|| |   | ' /
          | |_| | |_| | |__| |___| . \\​
           \\____|____/|_____\\____|_|\\_\\​

    Run `gdeck --help` to get started, or `gdeck tui` for the interactive UI.
  EOS
end
