# This file was generated by GoReleaser. DO NOT EDIT.
cask "gdeck" do
  version "0.1.3-rc.1"

  on_macos do
    on_intel do
      sha256 "008bf1951b3cf8d53c107e8dbff81b9fc1e01cd7d440b98b9d3e1a01ec57c240"
      url "https://github.com/Nunokawa-Lab/gdeck/releases/download/v#{version}/gdeck-darwin-amd64",
        verified: "github.com/Nunokawa-Lab/gdeck/"
      binary "gdeck-darwin-amd64", target: "gdeck"
    end
    on_arm do
      sha256 "b75c4f1ac3edbd91de98a13279561f80ff6410c3cf7250ceec138aaab1ac35b0"
      url "https://github.com/Nunokawa-Lab/gdeck/releases/download/v#{version}/gdeck-darwin-arm64",
        verified: "github.com/Nunokawa-Lab/gdeck/"
      binary "gdeck-darwin-arm64", target: "gdeck"
    end
  end

  on_linux do
    on_intel do
      sha256 "d88dca2f0df8d81999cc501473eb88e551f4ad023796a45e64d5e82e8bfcb2e8"
      url "https://github.com/Nunokawa-Lab/gdeck/releases/download/v#{version}/gdeck-linux-amd64",
        verified: "github.com/Nunokawa-Lab/gdeck/"
      binary "gdeck-linux-amd64", target: "gdeck"
    end
    on_arm do
      sha256 "173d37344ba984652a4e4fc29c924efc6cc807d80cbbf6e0504d6fc8c4e04720"
      url "https://github.com/Nunokawa-Lab/gdeck/releases/download/v#{version}/gdeck-linux-arm64",
        verified: "github.com/Nunokawa-Lab/gdeck/"
      binary "gdeck-linux-arm64", target: "gdeck"
    end
  end

  name "gdeck"
  desc "Lightweight API testing tool (CLI + TUI)"
  homepage "https://github.com/Nunokawa-Lab/gdeck"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gdeck"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    ____ ____  _____ ____ _  __
    / ___|  _ \| ____/ ___| |/ /
    | |  _| | | |  _|| |   | ' /
    | |_| | |_| | |__| |___| . \
    \____|____/|_____\____|_|\_\

    Run `gdeck --help` to get started, or `gdeck tui` for the interactive UI.
  EOS
end
